### ISSUE TITLE
搜索不管用了

### ISSUE THREAD

**Issue by happypeter** [happypeter/happycasts#296]

**Comment by billie66** [comment]
这个应该是 tinysou 出问题了，等等吧

**Comment by happypeter** [comment]
其实 happycasts 根本就用不着 es 这么强大的解决方案，来解决这么简单的问题。

http://lunrjs.com/ 应该就能满足要求，github help 就是用的这个方案。

**Comment by billie66** [comment]
看起来不错，我试着用一下

**Comment by billie66** [comment]
https://www.new-bamboo.co.uk/blog/2013/02/26/full-text-search-in-your-browser/

**Comment by billie66** [comment]
把 happycasts 的视频信息又重新上传到微搜索，搜索功能可以使用了
