### ISSUE TITLE
用 lunr.js 实现搜索

### ISSUE THREAD

**Issue by billie66** [happypeter/happycasts#301]
由于 #296 #300 出现的问题，用 lunr.js 来代替比较合适，毕竟数据量比较小

**Comment by billie66** [comment]
看了一下 https://help.github.com/ 中的 js 代码，用到有意思的功能 html5 的 worker,  还有 mustache

**Comment by happypeter** [comment]
因为有了 http://happycasts.net/all

所以如果只是实现视频名的搜索就没有意义了。

如果 lunr.js 用来来有难度，那搜索功能可以暂时不做，未来如果做也要做个能搜文字稿全文的。
